# Generated by Django 2.0.3 on 2018-10-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza_Regular',
            new_name='Regular_pizza',
        ),
        migrations.RenameModel(
            old_name='Subs',
            new_name='Sicilian_pizza',
        ),
        migrations.RenameModel(
            old_name='Pizza_Sicilian',
            new_name='Sub',
        ),
        migrations.RenameModel(
            old_name='Sub_Add_Ons',
            new_name='Sub_Add_On',
        ),
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
    ]
