# Generated by Django 2.0.3 on 2018-10-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181004_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
