# Generated by Django 2.0.3 on 2018-10-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181004_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steak_Sub_Add_On',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.RenameModel(
            old_name='Sub_Add_On',
            new_name='All_Sub_Add_On',
        ),
    ]
