# Generated by Django 2.0.3 on 2018-10-12 18:20

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181011_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('order', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='all_sub_add_on',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='steak_sub_add_on',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
