# Generated by Django 2.0.3 on 2018-10-16 14:16

import django.contrib.postgres.fields
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181012_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_sub_add_on',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='dinner_platter',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='regular_pizza',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='sicilian_pizza',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='steak_sub_add_on',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='item_id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order',
            field=django.contrib.postgres.fields.ArrayField(base_field=jsonfield.fields.JSONField(), size=None),
        ),
    ]
