# Generated by Django 2.0.3 on 2018-10-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orders_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Past_Orders',
        ),
    ]
