# Generated by Django 2.0.3 on 2018-10-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20181016_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_orders',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
