# Generated by Django 2.0.3 on 2018-10-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20181016_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner_platter',
            old_name='large_price',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='dinner_platter',
            old_name='small_price',
            new_name='small',
        ),
        migrations.RenameField(
            model_name='regular_pizza',
            old_name='large_price',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='regular_pizza',
            old_name='small_price',
            new_name='small',
        ),
        migrations.RenameField(
            model_name='sicilian_pizza',
            old_name='large_price',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='sicilian_pizza',
            old_name='small_price',
            new_name='small',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='large_price',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='small_price',
            new_name='small',
        ),
    ]
